name: CI - Integração Contínua
on:
  push:
    branches: [main, feature/ci-pipeline] # Define os branches que acionam o workflow quando há um push
  pull_request:
    branches: [main]
  workflow_dispatch: # Permite disparar o workflow manualmente (cria um botão "Run workflow" na interface do GitHub)
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Define o ambiente de execução como a última versão do Ubuntu
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Ação para fazer checkout do código-fonte do repositório

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Ação para configurar o ambiente Node.js
        with:
          node-version: 24
          cache: 'npm' #guarda as dependências em cache pra não baixar tudo do zero em cada execução

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:5173' # Espera o servidor de desenvolvimento estar disponível antes de rodar os testes

      - name: Salvar artefatos do Cypress em caso de falha
        uses: actions/upload-artifact@v4
        if: failure() # Só salva os artefatos se os testes falharem
        with:
          name: cypress-artefatos
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7 # Define por quanto tempo os artefatos ficarão disponíveis para download